language: ruby
os: linux
rvm:
- 2.4.6
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Wcb4c+1v+9mJT0vxv34VR06LTFecD6fOFWkF9/GrNuwFjVsAVtAxCZ8Us9NSZ0vn+jz2t6quHogl4fpcE5O+Oh8aB/6OtsBiE8ZphCd1gOl1wZVId/dJvJUfaP4ityL5beNVXCNqt+H72/V5p5ehYHbe+3GvYB+532QW+Ee0Mh5mch2L3Y7OessR/iwK2NGLILOlJck/v2RhPX5p+NvuvwKtRjLhtrZAxaRXulkVoRhh8a8Twndn5jTdLlyKJArcKYxP9bUMkbCdkchV2wQWAwuERKzSnh2XUepVpbrAkNJk1BypFXsSMGxIGz+3FNZQ8YI/PJ++R6zQy9kyUAFxsv4rvhdQk2XM4iqhVoD9eeShsGG3sGVV0nXicz9yLp1ps2g/WO03k6H870mCjZov3X1HnN4jMGJ6oYoRoZY+dZLODQjNihnlhBwQRELXejE4wA/Lc0/DNUZJa0rndz4nBFvbC8Z/bXQHhtLxSbF40NHe6d5iNTIj4Fgj4+DO05GOaPU2xQQV1mZMgUcgWiXPDQlI58oW7dHNzozZsmTAPZLmjyUDdGPNmOgW6tF+Lka5S0EAPiUqvh6d4IhuXvAOxyLLZYlcepQNZZjOli6/9Dz4UACKZ3KIvSTJbL3aAK02f8sQ/A0LT8VTy1+iovChC+l6P4j2ONmtfhuGmk7cz3s=

sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: "./_site"
  committer-from-gh: true
  user: Chen, KunYi(陳坤毅)
  email: kunyi@uwingstech.com
  on:
    branch: master
